export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILD = "REGISTER_FAILD";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILD = "LOGIN_FAILD";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAILD = "LOAD_USER_FAILD";
export const LOGOUT = "LOGOUT";
